<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_form_field']['more_attributes']			= array('Zusätzliche Attribute','Hier können Sie für das Formularfeld ein oder mehrere zusätzliche Attribute festlegen.');

?>